"""Request and response schemas for POST /v1/query.

The contract is frozen for v0 with conversation support added on 2026-04-14.
See `docs/api/query.md` for the canonical spec.
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import field_validator


def _require_non_blank(value: str) -> str:
    stripped = value.strip()
    if not stripped:
        raise ValueError("must not be blank")
    return stripped


class QueryRequestSchema(BaseModel):
    """Inbound payload for POST /v1/query.

    `session_id` is caller-owned and required on every request. The frontend
    generates it once per visitor (e.g. uuid in localStorage) and echoes it
    back on every call. It is the rate-limit key and the access-control scope
    for `conversation_id`.

    `conversation_id` is optional. If omitted, or if the supplied value does
    not belong to this `session_id`, the server silently mints a new one and
    returns it on the response. Callers that never want multi-turn memory
    simply never pass a `conversation_id` — each request is a fresh
    one-turn conversation.
    """

    model_config = ConfigDict(extra="forbid")

    question: str = Field(min_length=1, max_length=2000)
    session_id: str = Field(min_length=1, max_length=64)
    conversation_id: str | None = Field(default=None, max_length=64)

    @field_validator("question", "session_id")
    @classmethod
    def _trim_required(cls, value: str) -> str:
        return _require_non_blank(value)

    @field_validator("conversation_id")
    @classmethod
    def _trim_optional(cls, value: str | None) -> str | None:
        if value is None:
            return None
        stripped = value.strip()
        return stripped if stripped else None


class CitationSchema(BaseModel):
    """One retrieved chunk surfaced as a citation in the answer response."""

    model_config = ConfigDict(extra="forbid")

    document_id: str
    chunk_id: str
    chunk_order: int
    source_url: str
    title: str | None = None
    text: str
    ingested_at: datetime


# Client-facing status — simplified from the internal operational statuses
# stored in query_responses.status. The DB keeps the granular value
# (answered, no_answer, no_context, retrieval_failed, llm_failed, refused);
# the client gets the subset it can act on.
ClientStatus = Literal["answered", "no_answer", "refused", "error"]


class QueryResponseSchema(BaseModel):
    """Response payload for POST /v1/query.

    `status` tells the client what kind of outcome this was:
      - `answered` — retrieval + LLM produced a grounded answer.
      - `no_answer` — nothing relevant in the KB, or context too thin.
      - `refused` — safety gate blocked the request.
      - `error` — infrastructure failure (retrieval or LLM).

    `answer` is `None` when `status` is `no_answer` or `error`. When
    `status` is `refused`, `answer` carries the generic refusal text.

    `query_id` is `None` when `status` is `refused` — no query was persisted.

    `session_id` is echoed back unchanged. `conversation_id` is always set —
    either the one supplied by the caller (if it belonged to this session) or
    a freshly minted one. Callers should persist whatever is returned here
    and echo it on the next request to continue the conversation.

    `next_actions` is a list of 0–3 suggested follow-up prompts, generated by
    the answer-composition LLM call and grounded in the retrieved chunks. On
    no-answer responses it is always empty. Callers render them as clickable
    chips; each string is a complete first-person question under ~60 chars.
    """

    model_config = ConfigDict(extra="forbid")

    query_id: str | None
    session_id: str
    conversation_id: str
    status: ClientStatus
    answer: str | None
    citations: list[CitationSchema]
    confidence: Literal["high", "medium", "low"]
    next_actions: list[str] = Field(default_factory=list, max_length=3)
